import type { StatId } from '../types';

export const BASE_STATS: Record<StatId, number> = {
  maxHp: 0,
  atk: 0,
  matk: 0,
  physicalDef: 0,
  magicalDef: 0,
  strength: 15,
  agility: 15,
  intellect: 15,
  endurance: 5,
  illusionPower: 0,
  crit: 0,
  haste: 0,
  luck: 0,
  mastery: 0,
  versatility: 0,
  resist: 0,
  allAttrResist: 0,
  allAttrStr: 0,
  refinePhysAtk: 0,
  refineMagAtk: 0,
  refineDef: 0,
  receivedRecovery: 0,
  barrierStrength: 0,
  staminaRegen: 0,
  physicalEnhance: 0,
  magicalEnhance: 0,
  critDamageBonus: 0,
  luckyHitDamageBonus: 0,
  critRecoveryBonus: 0,
};
